if: tag IS present
os:
  - linux
  - osx
language: rust
rust:
  - nightly
cache: cargo
before_install:
  - echo -e "machine github.com\n  login $GITHUB_AUTH_TOKEN" > ~/.netrc
  - git config --local user.name "Cameron Bytheway"
  - git config --local user.email "bytheway.cameron@gmail.com"
  - git tag $TRAVIS_TAG-$TRAVIS_OS_NAME
install:
  - make wasp
script:
  - cargo build --release
  - strip ./target/release/wasp-cli
deploy:
  provider: releases
  api_key: 'GITHUB_AUTH_TOKEN'
  file: './target/release/wasp-cli'
  skip_cleanup: true
