if: tag IS present
env:
  global:
    - WASP_VERSION=50914429e20d2d3da5a956f12266223b7104dbcd
matrix:
  include:
    - os: linux
      dist: xenial
      env: WASP_RELEASE=wasp.deb
    - os: osx
      env: WASP_RELEASE=wasp-macos
    - os: windows
      env: WASP_RELEASE=wasp.exe
language: rust
rust:
  - nightly-2018-12-05
cache: cargo
before_install:
  - echo -e "machine github.com\n  login $GITHUB_AUTH_TOKEN" > .netrc
install:
  - ./install
script:
  - ./build
deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file: './release/$WASP_RELEASE'
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
