if: tag IS present
os:
  - linux
  - osx
language: rust
rust:
  - nightly-2018-11-26
cache: cargo
before_install:
  - echo -e "machine github.com\n  login $GITHUB_AUTH_TOKEN" > ~/.netrc
install:
  - make wasp
script:
  - make
deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file: './release/wasp'
  skip_cleanup: true
  overwrite: true
